### PR TITLE
convert from normal numbers to Roman Numerals

### PR DESCRIPTION
**Pull request by A-Annan**
- [x]  I have written unit test.

- [x]  I have then written logic code.

- [x]  I have added a documentation

### CODE REVIEW

**Comment by A-Annan** [comment]
@fengyuanyang please could you review this!

**Review by fengyuanyang — COMMENTED** [review]
> @fengyuanyang please could you review this!

Hi @farzado 
I have reviewed . Haven't you seen my comments there ?

**Comment by A-Annan** [comment]
@fengyuanyang Done 👍

**Comment by farzado** [comment]
> > @fengyuanyang please could you review this!
> 
> Hi @farzado
> I have reviewed . Haven't you seen my comments there ?

@fengyuanyang This is not my PR. Please check out the kata bowling PR which I created yesterday.

**Comment by fengyuanyang** [comment]
LGTM @A-Annan  
Thanks

**Pull request merged**
